// Indian payment and service integrations
export const INDIAN_INTEGRATIONS = {
  payments: {
    razorpay: {
      name: "Razorpay",
      description: "India's leading payment gateway",
      features: ["UPI", "Cards", "Net Banking", "Wallets"],
      logo: "🏦",
    },
    paytm: {
      name: "Paytm",
      description: "Digital payments and wallet",
      features: ["Paytm Wallet", "UPI", "Cards"],
      logo: "💳",
    },
    phonepe: {
      name: "PhonePe",
      description: "UPI and digital payments",
      features: ["UPI", "Wallet", "Cards"],
      logo: "📱",
    },
    googlepay: {
      name: "Google Pay",
      description: "UPI payments by Google",
      features: ["UPI", "Quick Pay"],
      logo: "🔍",
    },
  },
  shipping: {
    delhivery: {
      name: "Delhivery",
      description: "Pan-India logistics",
      deliveryTime: "2-5 days",
      logo: "🚚",
    },
    bluedart: {
      name: "Blue Dart",
      description: "Express delivery service",
      deliveryTime: "1-3 days",
      logo: "✈️",
    },
    dtdc: {
      name: "DTDC",
      description: "Domestic & international courier",
      deliveryTime: "2-4 days",
      logo: "📦",
    },
    indiapost: {
      name: "India Post",
      description: "Government postal service",
      deliveryTime: "3-7 days",
      logo: "📮",
    },
  },
  analytics: {
    clevertap: {
      name: "CleverTap",
      description: "Customer engagement platform",
      logo: "📊",
    },
    mixpanel: {
      name: "Mixpanel",
      description: "Product analytics",
      logo: "📈",
    },
  },
}

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Andaman and Nicobar Islands",
]
